set serveroutput on;
--Thủ tục để tạo user trong bảng nhân sự
CREATE OR REPLACE PROCEDURE SP_CREATE_NS AS
    CURSOR NS IS 
        SELECT MANV 
        FROM admin1.X_NHANSU 
        WHERE MANV NOT IN (SELECT USERNAME FROM ALL_USERS);
    STRSQL VARCHAR2(2000);
    MA_NS admin1.X_NHANSU.MANV%TYPE;
BEGIN
    OPEN NS;
    STRSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE';
    EXECUTE IMMEDIATE(STRSQL);
    LOOP
        FETCH NS INTO MA_NS;
        EXIT WHEN NS%NOTFOUND;
        STRSQL := 'CREATE USER '||MA_NS||' IDENTIFIED BY '||MA_NS;
        EXECUTE IMMEDIATE(STRSQL);
        STRSQL := 'GRANT CONNECT TO '||MA_NS;
        EXECUTE IMMEDIATE(STRSQL);
        DBMS_OUTPUT.PUT_LINE('User ' || MA_NS || ' đã được tạo thành công.');
    END LOOP;
    STRSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT" = FALSE';
    EXECUTE IMMEDIATE(STRSQL);
    CLOSE NS;
END;
/

--Thủ tục để xoá user trong bảng nhân sự
CREATE OR REPLACE PROCEDURE SP_DROP_NS AS
    CURSOR NV_USERS IS
        SELECT MANV AS USERNAME
        FROM admin1.X_NHANSU ;

    STRSQL VARCHAR2(2000);
BEGIN
    STRSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE';
    EXECUTE IMMEDIATE(STRSQL);
    FOR NV_USER IN NV_USERS LOOP
        STRSQL := 'DROP USER ' || NV_USER.USERNAME || ' CASCADE';
        EXECUTE IMMEDIATE(STRSQL);
        DBMS_OUTPUT.PUT_LINE('User ' || NV_USER.USERNAME || ' đã được xoá thành công.');
    END LOOP;
END;
/

exec SP_CREATE_NS;
/

--Check
--SELECT * FROM ALL_USERS WHERE USERNAME LIKE 'GV%' OR USERNAME LIKE 'GI%' OR USERNAME LIKE 'TDV%';
--Xoá khi cần
--exec SP_DROP_NS;

--Thủ tục để tạo user trong bảng sinh viên
CREATE OR REPLACE PROCEDURE SP_CREATE_SV AS
    CURSOR SV IS 
        SELECT MASV
        FROM admin1.X_SINHVIEN
        WHERE MASV NOT IN (SELECT USERNAME FROM ALL_USERS);
    STRSQL VARCHAR2(2000);
    MA_SV admin1.X_SINHVIEN.MASV%TYPE;
BEGIN
    OPEN SV;
    STRSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE';
    EXECUTE IMMEDIATE(STRSQL);
    LOOP
        FETCH SV INTO MA_SV;
        EXIT WHEN SV%NOTFOUND;
        STRSQL := 'CREATE USER '||MA_SV||' IDENTIFIED BY '||MA_SV;
        EXECUTE IMMEDIATE(STRSQL);
        STRSQL := 'GRANT CONNECT TO '||MA_SV;
        EXECUTE IMMEDIATE(STRSQL);
        DBMS_OUTPUT.PUT_LINE('User ' || MA_SV || ' đã được tạo thành công.');
    END LOOP;
    STRSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT" = FALSE';
    EXECUTE IMMEDIATE(STRSQL);
    CLOSE SV;
END;
/

--Thủ tục để xoá user trong bảng sinh viên
CREATE OR REPLACE PROCEDURE SP_DROP_SV AS
    CURSOR SV_USERS IS
        SELECT MASV AS USERNAME
        FROM admin1.X_SINHVIEN ;

    STRSQL VARCHAR2(2000);
BEGIN
    STRSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE';
    EXECUTE IMMEDIATE(STRSQL);
    FOR SV_USER IN SV_USERS LOOP
        STRSQL := 'DROP USER ' || SV_USER.USERNAME || ' CASCADE';
        EXECUTE IMMEDIATE(STRSQL);
        DBMS_OUTPUT.PUT_LINE('User ' || SV_USER.USERNAME || ' đã được xoá thành công.');
    END LOOP;
END;
/

exec SP_CREATE_SV;
/

--Check
--SELECT * FROM ALL_USERS WHERE USERNAME LIKE 'SV%';
--Xoá khi cần
--exec SP_DROP_SV;